export const routesAccessMap = new Map([
    ["403",                     {hasAccess: ["guest", "user", "admin", "boss"], menuLabel: "", uses: new Map([["other", 0]]) }],
    ["404",                     {hasAccess: ["guest", "user", "admin", "boss"], menuLabel: "", uses: new Map([["other", 0]]) }],
    ["main-page",               {hasAccess: ["guest", "user", "admin", "boss"], menuLabel: "", uses: new Map([["other", 0]]) }],
    ["auth-user-page",          {hasAccess: ["guest", "user", "admin", "boss"], menuLabel: "", uses: new Map([["other", 999]]) }],
    ["advertiser-page",         {hasAccess: ["guest", "user", "admin"], mainMenuLabel: "Рекламодателям", uses: new Map([["top-menu", 20], ["compact-menu", 20]]) }],
    ["sp-offers-page",          {hasAccess: ["guest", "user", "admin"], mainMenuLabel: "SP офферы", uses: new Map([["top-menu", 10], ["compact-menu", 10]]) }],
    ["vacancies-page",          {hasAccess: ["guest", "user", "admin"], mainMenuLabel: "Вакансии", uses: new Map([["top-menu", 30], ["compact-menu", 30]]) }],
    ["user-main",               {hasAccess: ["user", "boss"],menuLabel: "Главная",uses: new Map([["top-menu", 10], ["compact-menu", 10],]), },],
    ["admin-main",              {hasAccess: ["admin"],menuLabel: "Главная", mainMenuLabel: "Личный кабинет",uses: new Map([["top-menu", 10], ["compact-menu", 10]]), },],
    ["user-finance",            {hasAccess: ["user"],menuLabel: "Финансы",uses: new Map([["top-menu", 20],["compact-menu", 20],]),},],
    ["admin-payout",   {hasAccess: ["admin"],menuLabel: "Выплаты",uses: new Map([["top-menu", 21], ["compact-menu", 21],]),},],
    ["user-statistics",         {hasAccess: ["user"],menuLabel: "Статистика",uses: new Map([["top-menu", 30],["compact-menu", 30],]),},],
    ["user-extended-statistics",{hasAccess: ["boss"],menuLabel: "Статистика",uses: new Map([["top-menu", 31],["compact-menu", 31],]),},],
    ["user-offers",             {hasAccess: ["boss"],menuLabel: "Офферы",uses: new Map([["top-menu", 40],["compact-menu", 40],]),},],
    ["admin-offer-toggle", {hasAccess: ['admin'], menuLabel: 'Офферы', uses: new Map([["top-menu", 10],["compact-menu", 10],])}],
    ["user-profile",            {hasAccess: ["user", "boss"],menuLabel: "Личный кабинет",uses: new Map([["top-right-menu", 10],["compact-menu", 60],]),},],
    ["admin-settings",          {hasAccess: ["admin"],menuLabel: "Настройки",uses: new Map([["top-menu", 50],["compact-menu", 50],]),},],
    ["user-offer-detail", {hasAccess: ['user'], menuLabel: '', uses: new Map([["other", 0]])}],
]);
